env:
  global:
    - CC_TEST_REPORTER_ID=51e7a765847b265522736cd407ffcdda461240971306f662d20ee2698bf4b815
language: node_js
node_js: 
  - "8"
cache:
  directories:
    - "node_modules"
before_script:
  - psql -c 'create database morerecipes;' -U postgres 
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_success:
  - npm run coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
services:
  - postgresql
addons:
  postgresql: "9.6"